config/routes.rb
Rails.application.routes.draw do
    get 'wellcome/index'
    get 'log_out' => 'sessions#destroy', :as => 'log_out'
    # get 'log_in' => 'sessions#new', :as => 'log_in'
    # get 'sign_up' => 'users#new', :as => 'sign_up'
    get 'log_in' => 'sessions#create', :as => 'log_in'
    #  shallow do
    get 'json_get' => 'products#getjson', :as => 'json_get'
    get 'json_put' => 'products#putjson', :as => 'json_put'
    patch 'json_put2' => 'products#putjson2', :as => 'json_put2'
    patch 'json_put1' => 'products#putjson1', :as => 'json_put1'
    root 'home#index'
    resources :stores
    resources :products
    resources :users
end
# end

app/models/store.rb
class Store < ApplicationRecord
    has_many :products
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
    before_action :set_store, only: [:show, :edit, :update, :destroy]

    def index
        @stores = Store.all
    end

    def show
        @store = Store.find(params[:id])
    end

    def new
        @store = Store.new
    end

    def edit
        @store = Store.find(params[:id])
     end

    def create
        @store = Store.new(store_params)

        respond_to do |format|
            if @store.save
                format.html { redirect_to @store, notice: 'Store was successfully created.' }
                format.json { render :show, status: :created, location: @store }
            else
                format.html { render :new }
                format.json { render json: @store.errors, status: :unprocessable_entity }
            end
        end
    end

    def update
        @store = Store.find(params[:id])

        if @store.update(store_params)
            redirect_to @store
        else
            render 'edit'
        end
    end

    def destroy
        @store.destroy
        respond_to do |format|
            format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private

    def set_store
        @store = Store.find(params[:id])
    end

    def store_params
        params.require(:store).permit(:id, :name, :kind, :status)
         end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_for(store) do |f| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :Name %><br>
    <%= f.text_field :name %>
      </p>

      <p>
        <%= f.label :Kind %><br>
        <%= f.text_field :kind %>
      </p>

      <p>
        <%= f.label :Status %><br>
        <%= f.text_field :status %>

      </p>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Show', store_path, method: :get %> |
<%= link_to 'Back', stores_path, method: :get %>

app/views/stores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stores</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Kind</th>
      <th>Status</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.name %></td>
        <td><%= store.kind %></td>
        <td><%= store.status %></td>

        <td><%= link_to 'Show', store_path(store), method: :get %></td>
        <td><%= link_to 'Edit', edit_store_path(store), method: :get %></td>
        <td><%= link_to 'Destroy', store_path(store), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Store', new_store_path %><br><br>
<%= link_to 'Home Hardware', wellcome_index_path %>

app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>
<h1>STORE DATA</h1>
<p>
  <strong>Name:</strong>
  <%= @store.name %>
</p>
<p>
  <strong>Kind</strong>
  <%= @store.kind  %>
</p>

<p>
  <strong>Status:</strong>
  <%= @store.status  %>
</p>

<%= link_to 'Edit', edit_store_path %> |
<%= link_to 'Back', stores_path %>