config/routes.rb
Rails.application.routes.draw do
    get 'wellcome/index'
    get 'log_out' => 'sessions#destroy', :as => 'log_out'
    # get 'log_in' => 'sessions#new', :as => 'log_in'
    # get 'sign_up' => 'users#new', :as => 'sign_up'
    get 'log_in' => 'sessions#create', :as => 'log_in'
    #  shallow do
    get 'json_get' => 'products#getjson', :as => 'json_get'
    get 'json_put' => 'products#putjson', :as => 'json_put'
    patch 'json_put2' => 'products#putjson2', :as => 'json_put2'
    patch 'json_put1' => 'products#putjson1', :as => 'json_put1'
    root 'home#index'
    resources :stores
    resources :products
    resources :users
end
# end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :store
    validates :name, :description, :price, :quantity, presence: true
    attr_accessor :remember
    attr_reader :remember
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :set_product, only: [:show, :edit, :update, :destroy]
    require 'rest-client'
    require 'json'

    def index
        @products = Product.all
    end

    def show
        @product = Product.find(params[:id])
    end

    def new
        @product = Product.new
    end

    def edit
        @product = Product.find(params[:id])
     end

    def create
        @product = Product.new(product_params)

        respond_to do |format|
            if @product.save
                format.html { redirect_to @product, notice: 'Product was successfully created.' }
                format.json { render :show, status: :created, location: @product }
            else
                format.html { render :new }
                format.json { render json: @product.errors, status: :unprocessable_entity }
            end
        end
    end

    def update
        @product = Product.find(params[:id])

        if @product.update(product_params)
            redirect_to @product
        else
            render 'edit'
        end
    end

    def destroy
        @store.destroy
        respond_to do |format|
            format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    def getjson
        @products = RestClient.get 'http://192.168.35.31:3000/json_put'
        puts 'antes'
        puts @products
        @product = JSON.parse(@products)
        render :index1
     end

    def putjson
        # if params_key?(:product_id)

        #  else
        @product = Product.all
        render json: @product
        end
    # end

    def putjson1
        quantid = params['key1']
        puts @product
        @product = Product.find_by_id(quantid)
        puts @product.quantity

        puts @product.quantity
        @product = @product.update(quantity: @product.quantity -= 1)
        render json: @product
      end

    def putjson2
        puts params[:id]
        @product = RestClient.patch 'http://192.168.35.31:3000/json_put1', 'key1' => params[:id]
        redirect_to json_get_path
      end

    private

    def set_product
        @product = Product.find(params[:id])
    end

    def product_params
        params.require(:product).permit(:id, :name, :store_id, :description, :price, :quantity)
         end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this Product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :Name %><br>
    <%= f.text_field :name %>
      </p>

      <p>
        <%= f.label :Description %><br>
        <%= f.text_field :description %>
      </p>

      <p>
        <%= f.label :price %><br>
        <%= f.text_field :price %>

      </p>
      <p>
        <%= f.label :Quantity %><br>
        <%= f.text_field :quantity %>

      </p>
      <p>
      <%= f.label :Store_id %><br>
      <%= f.text_field :store_id %>
    </p>



  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Show', store_path %> |
<%= link_to 'Back', stores_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Quantity</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= product.quantity %></td>
        <td><%= link_to 'Show', product_path(product) %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product_path(product), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %><br><br>
<%= link_to 'Home Hardware', wellcome_index_path %>

app/views/products/index1.html.erb
<p id="notice"><%= notice %></p>
<h1>Products</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Quantity</th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    <% @product.each do |product| %>
      <tr>
        <td><%= product["name"] %></td>
        <td><%= product["description"] %></td>
        <td><%= product["price"] %></td>
        <td><%= product["quantity"] %></td>
        <td><%= link_to 'Comprar', json_put2_path(:id => product["id"],:name => product["name"]), method: :patch  %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Product', new_product_path %><br><br>
<%= link_to 'Home Hardware', wellcome_index_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<h1>PRODUCT DATA</h1>
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>
<p>
  <strong>Description:</strong>
  <%= @product.description  %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price  %>
</p>
<p>
  <strong>Quantity:</strong>
  <%= @product.quantity  %>
</p>
<%  store=Store.find(@product.store_id) %>
<p>
  <strong>Store-id:</strong>
  <%= @product.store_id  %>
</p>
<p>
  <strong>Store-name:</strong>
  <%= store.name  %>
</p>


<%= link_to 'Edit', edit_product_path %> |
<%= link_to 'Back', products_path %>